[package]
name = "mellow"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "lib/syntax",
    "lib/assembly",
]

[dependencies]
syntax = { path = "lib/syntax" }
assembly = { path = "lib/assembly" }
