[package]
name = "mellow"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ 
    "lib/syntax",
    "lib/ir",
    "lib/assembly",
]

[dependencies]
syntax = { path = "lib/syntax" }
ir = { path = "lib/ir" }
assembly = { path = "lib/assembly" }