[package]
name = "mellow"
version = "0.1.0"
edition = "2024"

[workspace]
members = [ 
    "lib/syntax",
    "lib/ir",
    "lib/assembly", "lib/mellow-lex", "lib/mellow-parse",
]

[dependencies]
syntax = { path = "lib/syntax" }
ir = { path = "lib/ir" }
assembly = { path = "lib/assembly" }
